language: python
python:
  - "2.7"
  - "3.5"
#command to install dependencies
  - pip install -r travis/requirements.txt
  - pip install coveralls
#command to run tests
script: 
  - python test_rpn.py
after_success:
  - coveralls
